"""Initial financial models

Revision ID: 7f2319c9d3f6
Revises: 
Create Date: 2025-11-11 18:40:59.115948
"""

from alembic import op
import sqlalchemy as sa
from svc_infra.db.sql.types import GUID  # portable UUID across PG/MySQL/SQLite


# revision identifiers, used by Alembic.
revision = '7f2319c9d3f6'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
